espectador_quando_morrer: true
maximo_vida: 6
saturacao: true

sniper:
  items:
  portal:
    block: 'WHITE_TERRACOTTA'
  spawn:
  sniper_spawn:

randomblocks:
  timer: 5
  blacklist: [
    'BEDROCK',
    'BARRIER',
    'COMMAND_BLOCK',
    'STRUCTURE_BLOCK',
    'JIGSAW',
    'END_PORTAL',
    'END_PORTAL_FRAME',
    'NETHER_PORTAL',
    'SPAWNER',
    'LIGHT'
  ]
